# Generated by Django 5.0.6 on 2024-07-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=155)),
                ('telefone', models.CharField(max_length=155)),
                ('sugestão', models.CharField(max_length=155)),
            ],
        ),
    ]
